
!include <win32.mak>

#Compiler
CC=cl.exe

#Linker
LINK=link.exe

# Link the object files into a binary
app: unittest.o
	$(LINK) /OUT:unittest.exe unittest.obj

#Compile the source files into object files
unittest.o: unittest.c
	$(CC) /c unittest.c 

# Clean target

clean :
		del unittest.o unittest.obj 
